### ISSUE TITLE
HA 0.88.2 - Card Not Functioning

### ISSUE THREAD

**Issue by nurbanasaurus** [thomasloven/lovelace-color-picker#2]
I have updated the modules affiliated with this including the required components, "card-tools" and still not able to get this to present correctly after updates.

![image](https://user-images.githubusercontent.com/1489781/53690040-051d2a00-3d31-11e9-80ce-411caf137471.png)

Is there something I am missing?

**Comment by thomasloven** [comment]
There are some debugging steps described in the linked installation instructions, but I kind of don't support this anymore. Here's a much better one: https://community.home-assistant.io/t/light-entity-card/96146
