### ISSUE TITLE
Clicking the card pops up the entity

### ISSUE THREAD

**Issue by math0ne** [thomasloven/lovelace-color-picker#3]
Any way to address that?

**Comment by thomasloven** [comment]
Can't reproduce.

**Comment by math0ne** [comment]
I experience this issue as well.

**Comment by thomasloven** [comment]
This card is deprecated and not supported. I suggest you use https://community.home-assistant.io/t/light-entity-card/96146 or https://github.com/thomasloven/lovelace-more-info-card instead.
